DROP TABLE IF EXISTS TEST;

CREATE TABLE IF NOT EXISTS TEST(
	id INT NOT NULL AUTO_INCREMENT,PRIMARY KEY(id)
);

INSERT INTO TEST (id) VALUES ('1');
INSERT INTO TEST (id) VALUES ('2');


INSERT INTO TEST (id) VALUES ('3');
INSERT INTO TEST (id) VALUES ('4');
INSERT INTO TEST (id) VALUES ('5');

